name: attendance_app
version: 1.0.0+1
publish_to: none
description: A Flutter project for attendance application.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter: 
    sdk: flutter

  material_design_icons_flutter: ^5.0.6595

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/attendance-machine.png

